FROM alpine:latest
MAINTAINER CCZZRS <cczzrs@aliyun.com>

WORKDIR /app
VOLUME /app

RUN apk add --update mysql mysql-client && rm -f /var/cache/apk/*
COPY my.cnf /etc/mysql/my.cnf
COPY build_mysql.sh /build_mysql.sh

EXPOSE 3306
CMD ["/build_mysql.sh"]