# Generated by Django 2.0.7 on 2018-08-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationRecord',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('hash_id', models.CharField(blank=True, max_length=64, null=True)),
                ('resolve_date_begin', models.DateTimeField(blank=True, null=True)),
                ('resolve_date_end', models.DateTimeField(blank=True, null=True)),
                ('run_time', models.DateTimeField(blank=True, null=True)),
                ('service_type', models.CharField(blank=True, max_length=100, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('base_sources', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'db_table': 'operation_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpidersBaseSource',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('hash_id', models.CharField(blank=True, max_length=64, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=500, null=True)),
                ('service_type', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('url_source', models.CharField(blank=True, max_length=500, null=True)),
                ('url_type', models.CharField(blank=True, max_length=2, null=True)),
                ('resolve_type', models.CharField(blank=True, max_length=2, null=True)),
                ('resolve_rule', models.CharField(blank=True, max_length=50, null=True)),
                ('resolve_source', models.CharField(blank=True, max_length=5000, null=True)),
                ('resolve_sources', models.CharField(blank=True, max_length=5000, null=True)),
                ('resolve_next_page', models.CharField(blank=True, max_length=500, null=True)),
                ('resolve_page_wait', models.CharField(blank=True, max_length=500, null=True)),
                ('run_time', models.DateTimeField(blank=True, null=True)),
                ('run_count', models.IntegerField(blank=True, null=True)),
                ('content_page_rule', models.CharField(blank=True, max_length=5000, null=True)),
                ('bz1', models.CharField(blank=True, max_length=255, null=True)),
                ('bz2', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'spiders_base_source',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpidersNews',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('hash_id', models.CharField(blank=True, max_length=64, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('news_title', models.TextField(blank=True, null=True)),
                ('news_type', models.CharField(blank=True, max_length=255, null=True)),
                ('news_date', models.DateTimeField(blank=True, null=True)),
                ('url_source', models.CharField(blank=True, max_length=255, null=True)),
                ('url_type', models.CharField(blank=True, max_length=255, null=True)),
                ('resolve_type', models.CharField(blank=True, max_length=255, null=True)),
                ('resolve_rule', models.CharField(blank=True, max_length=255, null=True)),
                ('resolve_source', models.CharField(blank=True, max_length=255, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('bz1', models.CharField(blank=True, max_length=255, null=True)),
                ('bz2', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'spiders_news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpidersNewsContent',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('hash_id', models.CharField(blank=True, max_length=64, null=True)),
                ('news_content', models.TextField(blank=True, null=True)),
                ('news_type', models.CharField(blank=True, max_length=255, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('url_source', models.CharField(blank=True, max_length=255, null=True)),
                ('url_type', models.CharField(blank=True, max_length=255, null=True)),
                ('bz1', models.CharField(blank=True, max_length=255, null=True)),
                ('bz2', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'spiders_news_content',
                'managed': False,
            },
        ),
    ]
